name: Latest blog posts

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    name: Pull latest posts from rebjak.com RSS

    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://rebjak.com/en/rss.xml"
          max_post_count: 5
          template: "- [$title]($url) <sub>$date</sub>$newline"
          date_format: "mmm d, yyyy"
          commit_message: "docs: update README with latest blog posts"
